language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - realpath
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    # osx_image: xcode10.1
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"

  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  #exclude:
  #  - compiler: gcc
# before_install:
install:
  - git clone --depth=1 --branch=master https://github.com/openFrameworks/openFrameworks.git ~/openFrameworks
  - /usr/bin/env bash ~/openFrameworks/scripts/ci/addons/install.sh
  - git clone https://github.com/bakercp/ofx.git ~/openFrameworks/scripts/ofx
script:
  -  /usr/bin/env bash ~/openFrameworks/scripts/ofx/ofx ci script ${TRAVIS_REPO_SLUG#*/}
# after_script:
# after_success:
# after_failure:

git:
  depth: 1
  quiet: true
